//AUTOGENERATED - DO NOT TOUCH!
public struct InputAction {
    public const int Horizontal = 0;
    public const int Vertical = 1;
    public const int Jump = 2;
    public const int Attack1 = 3;
    public const int Attack2 = 4;
    public const int Special = 5;
    public const int MenuHorizontal = 6;
    public const int MenuVertical = 7;
    public const int MenuAccept = 8;
    public const int MenuCancel = 9;
    public const int Menu = 10;
}
